from __future__ import annotations

import operator
from collections.abc import Iterable, Sequence
from typing import SupportsIndex, cast

from . import native
from .source import Source, normalize_sources

__all__ = ["Files", "Index"]


Index = SupportsIndex | Sequence[SupportsIndex] | None
Files = str | Sequence[str] | None


def _index_integer(value: object) -> int:
    if isinstance(value, bool):
        raise TypeError
    return operator.index(cast(SupportsIndex, value))


def normalize_index(value: Index) -> str | None:
    if value is None:
        return None
    try:
        return str(_index_integer(value))
    except TypeError:
        pass
    try:
        values = list(cast(Iterable[object], value))
        indexes = [_index_integer(item) for item in values]
    except TypeError:
        raise TypeError("idx must be an integer or a two-element range") from None
    if len(indexes) != 2:
        raise TypeError("idx must be an integer or a two-element range")
    return f"[{indexes[0]}, {indexes[1]}]"


def normalize_files(value: Files) -> list[str] | None:
    if value is None:
        return None
    try:
        values = [value] if isinstance(value, str) else list(value)
    except TypeError:
        raise TypeError("files must be a string or a sequence of strings") from None
    if not all(isinstance(item, str) for item in values):
        raise TypeError("files must be a string or a sequence of strings")
    return values


def build_native_sql(
    path: Source,
    *,
    idx: Index = None,
    level: str | None = None,
    pivoted: bool = True,
    files: Files = None,
    location: bool = True,
) -> str:
    """Return the low-level query generated by the native core."""
    if not isinstance(location, bool):
        raise TypeError("location must be a boolean")
    index = normalize_index(idx)
    selected_files = normalize_files(files)
    datasets = [native.NativeDataset(source) for source in normalize_sources(path)]
    return native.sql(
        datasets,
        idx=index,
        level=level,
        pivoted=pivoted,
        files=selected_files,
        location=location,
    )
